# Generated by Django 4.0.4 on 2022-05-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_done_list_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
