# Generated by Django 4.0.4 on 2022-05-31 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_folder_is_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfolder',
            old_name='is_accepted',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='sharedfolder',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedfolder',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedfolder',
            name='shared_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
